### ISSUE TITLE
Cannot run the project

### ISSUE THREAD

**Issue by Avin-Techv** [bfincher/html_browser#1]
I have cloned the project followed by installing the packages in requirements.txt file and now i am getting an error like this

ImportError: No module named 'html_browser_site.local_settings'

please specify the steps to run the project

**Comment by bfincher** [comment]
Sorry, I plan on getting back to this project soon.  This should have had instructions and/or an install script.  Just copy settings.py to local_settings.py

**Comment by bfincher** [comment]
After cloning, copy one of the local settings examples to local_settings.py.  
cd html_browser_site
cp local_settings_cygwin.py local_settings.py

Then:
python manage.py migrate
python manage.py runserver 0.0.0.0:8000
